# 运行阶段
FROM hub.glodon.com/glodon-pub/debian:stable-slim-base

# 定义构建参数（由 buildx 自动注入）
ARG TARGETOS
ARG TARGETARCH

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     ca-certificates \
#     curl \
#     && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# 从本地复制对应架构的二进制文件
COPY bin/${TARGETOS}/${TARGETARCH}/agent .

# 复制配置文件
COPY configs/agent-plugins.yaml /app/configs/agent-plugins.yaml
COPY configs/agent-security.yaml /app/configs/agent-security.yaml

# 创建数据目录
RUN mkdir -p /app/data

ENV CLOUD_URL=http://cloud:8080
ENV AGENT_ID=
ENV AGENT_NAME=agent
ENV K8S_CLUSTER_NAME=
#  nsenter -t 1 -m  -u -i -n  bash
CMD ["sh", "-c", "exec ./agent -cloud \"${CLOUD_URL}\" -id \"${AGENT_ID}\" -name \"${AGENT_NAME}\""]

